batch_size: 2
data: spider_1000
learning_rate: 0.0005
model: /home/user/mzs_h/model/second-gla-1.3B-100B/gla-1.3B-100B
no_save: false
num_epochs: 10
peft: cfg/peft/lora/r8/lora_gla_qkvo.json
prec: bf16
