
batch_size: 4
learning_rate: 0.0003
model: /home/user/mzs_h/model/second-gla-1.3B-100B/gla-1.3B-100B
no_save: false
num_epochs: 10
peft: cfg/my_lora_exp/peft/lora_omlp_plus_g_plus_gk_r8_alpha8.json
prec: bf16
