batch_size: 4
data: glue-tvt_cola
learning_rate: 0.0005
model: /home/user/mzs_h/model/second-gla-1.3B-100B/gla-1.3B-100B
peft: cfg/my_lora_exp/peft/lora_mixed_qkvo_gates_mlp_aux_r8a16_r4a8.json
prec: bf16
num_epochs: 10
no_save: false


