batch_size: 4
data: glue-tvt_cola
learning_rate: 0.001
model: /home/user/mzs_h/model/second-gla-1.3B-100B/gla-1.3B-100B
no_save: false
num_epochs: 10
peft: cfg/peft/lora/r4/lora_gla_qkvo.json
prec: bf16


